//Question and Answer array...
//

const qstnAns = [
  {
    id: "001",
    question: "Pipes A and B can fill a tank in 10 hours and x hours respectively. Pipe C alone can empty the full tank in 15 hours. When all the three pipes are opened simultaneously for 8 hours, 60% of the tank can be filled. In how many hours can pipes B and C together empty two-fifth of the tank?",
    a: "18",
    b: "12",
    c: "15",
    d: "16",
    answer: "d",
  },
  {
    id: "002",
    question: "Pipes A and B can fill a tank in 9 hours and 15 hours, respectively. Both pipes were opened at the same time. After some time, it was found that there was a leak at the bottom of the tank which was capable of emptying the fully filled tank in 22.5 hours. It was then repaired. If the tank got filled in a total time of 6 hours, then after how much time was the leakage repaired?",
    a: "1.5 hrs",
    b: "1.25 hrs",
    c: "2.5 hrs",
    d: "Option b and c",
    answer: "a",
  },
  {
    id: "003",
    question: "Two pipes A and B can fill a cistern in 6 and 8 minutes respectively. If A starts the work and they be turned on alternatively for one minute each, how long will it take to fill the cistern?",
    a: "24/7 Minutes",
    b: "27/4 Minutes",
    c: "6 Minutes",
    d: "None of above",
    answer: "b",
  },
  {
    id: "004",
    question: "Pipes A and B can empty a full tank in 16 hours and 24 hours, respectively. Pipe C alone can fill the empty tank in 4 hours. If A, B and C are opened together, the tank will be 35% full after:",
    a: "16/5 hrs",
    b: "17/5 hrs",
    c: "12/5",
    d: "19/5",
    answer: "c",
  },
  {
    id: "005",
    question: "A pond is fitted with two pipes. The first pipe can fill the pond completely in 45 minutes and the second pipe can empty the full pond in one hour. If both the pipes are opened alternatively for one minute, then in how many hours the empty pond will be filled completely?",
    a: "2 hrs 55 min",
    b: "5 hrs 53 min",
    c: "3 hrs 40 min",
    d: "4 hrs 22 min",
    answer: "b",
  },
  {
    id: "006",
    question: "A cistern has two pipes one can fill it with water in 16 hours and other can empty it in 10 hours. In how many hours will the cistern be emptied if both the pipes are opened together when 1/5th of the cistern is already filled with water?",
    a: "11.4 hrs",
    b: "3.66 hrs",
    c: "5.33 hrs",
    d: "8.33 hrs",
    answer: "c",
  },
  {
    id: "007",
    question: "Pipes A and B can fill a tank with water in 30 minutes and 40 minutes, respectively, while pipe C can drain off 51 litres of water per minute. If all the three pipes are opened together, the tank is filled in 90 minutes. What is the capacity (in litres) of the tank?",
    a: "900 ltr",
    b: "864 ltr",
    c: "720 ltr",
    d: "1080 ltr",
    answer: "d",
  },
  {
    id: "008",
    question: "Two inlet pipes A and B together can fill a tank in 24 min, and it takes 6 min more when one leak is developed in the tank. Find the time taken by leak alone to empty the tank.",
    a: "2 hrs",
    b: "4 hrs",
    c: "2.5 hrs",
    d: "3 hrs",
    answer: "a",
  },
  {
    id: "009",
    question: "Three flood gates A, B and C can fill a reservoir in 6 hours. After working at it together for 2 hours, flood gate C is closed. Flood gates A and B can fill the remaining part in 7 hours. The number of hours taken by flood gate C alone to fill the reservoir is:",
    a: "16",
    b: "14",
    c: "10",
    d: "12",
    answer: "b",
  },
  {
    id: "010",
    question: "Two pipes A and B together can fill a tank in 6 hours. If pipe A can fill 5 hours faster than pipe B, in how many hours pipe B alone can fill the tank?",
    a: "15",
    b: "10",
    c: "18",
    d: "12",
    answer: "a",
  },

  // Above datas are Pipe and cistern data...

  {
    id: "011",
    question: "A bag contains 5 red balls and some blue balls. If the probability of drawing a blue ball from the bag is four times that of a red ball, then the number of blue balls in the bag is",
    a: "10",
    b: "40",
    c: "20",
    d: "15",
    answer: "c",
  },
  {
    id: "012",
    question: "A dice is thrown randomly. What is the probability that the number shown on the dice is not divisible by 3?",
    a: "1/3",
    b: "2/3",
    c: "1/4",
    d: "1/2",
    answer: "b",
  },
  {
    id: "013",
    question: "The cards bearing letters of the word 'MATHEMATICS' are placed in a bag. A card is taken out from the bag without looking into the bag at random. What is the probability of getting any vowel bearing card?",
    a: "2/11",
    b: "9/11",
    c: "7/11",
    d: "4/11",
    answer: "d",
  },
  {
    id: "014",
    question: "5 coins are tossed simultaneously. Find the probability of exactly 3 heads?",
    a: "5/16",
    b: "6/16",
    c: "9/16",
    d: "7/16",
    answer: "a",
  },
  {
    id: "015",
    question: "Ajay rolled two dice together. What is the probability that first dice showed a multiple of 3 and the second dice showed an even number?",
    a: "5/6",
    b: "1/3",
    c: "1/6",
    d: "1/9",
    answer: "c",
  },
  {
    id: "016",
    question: "The probability of Sita, Gita and Mita passing a test is 60%, 40% and 20% respectively. What is the probability that at Sita and Gita will pass the test and Mita will not? is",
    a: "38.4%",
    b: "60%",
    c: "4.8%",
    d: "19.2%",
    answer: "d",
  },
  {
    id: "017",
    question: "Two unbiased dice are rolled simultaneously. Find the probability of getting sum greater than 5.",
    a: "13/18",
    b: "23/36",
    c: "7/9",
    d: "5/9",
    answer: "a",
  },
  {
    id: "018",
    question: "A goldsmith has a bag, which contains some colourful stones. It contains 4 White and 8 Black stones. There is another bag which contains 5 White and 5 Black stones. One stone is to drawn from either of the two bags. What is the probability of drawing a White stone?",
    a: "7/13",
    b: "8/13",
    c: "5/12",
    d: "11/12",
    answer: "c",
  },
  {
    id: "019",
    question: "A man and his wife appear in an interview. The probability of husband's selection is 1/7 and the probability of wife's selection is 1/5. What is the probability that only one of them is selected?",
    a: "2/7",
    b: "1/25",
    c: "1/3",
    d: "1/35",
    answer: "a",
  },
  {
    id: "020",
    question: "There is a dart board with five concentric circles of radius 4cm, 6cm, 10cm, 14cm and 24cm. What is the probability that a dart thrown will hit the board between smallest and second largest circle?",
    a: "9/19",
    b: "49/144",
    c: "83/144",
    d: "5/16",
    answer: "d",
  },
  // Above datas are Probability data...


  {
    id: "021",
    question: "The ratio of the present ages of Rani and Rohan is 3: 4. After 3 years the ratio will become 4: 5. The ratio of their ages 24 years from now will be_______.",
    a: "11:12",
    b: "12:13",
    c: "10:11",
    d: "10:12",
    answer: "a",
  },
  {
    id: "022",
    question: "The sum of the ages of Neeraj and Suresh is twice the sum of their ages 6 years ago. What is Suresh's age, if Neeraj is 10 years older than Suresh?",
    a: "3 Years",
    b: "4 Years",
    c: "7 Years",
    d: "9 Years",
    answer: "c",
  },
  {
    id: "023",
    question: "Seven years ago, the ratio of the age of A and B is 8: 9. After 7 years, the ratio of the age of A and B is 10: 11. After 'x' years from now, the age of B is 15/14 of the age of A. Find the value of 'x'.",
    a: "30 Years",
    b: "35 Years",
    c: "28 Years",
    d: "44 Years",
    answer: "b",
  },
  {
    id: "024",
    question: "Four years ago, the age of the mother was 13 times the age of her daughter. Two years hence, the mother's age will be 4 times the daughter's age. After how many years will the mother's age be 3 times that of her daughter?",
    a: "4",
    b: "7",
    c: "5",
    d: "6",
    answer: "d",
  },
  {
    id: "025",
    question: "Murali's present age is half of his father's age. before 10 years, his father's age was thrice his age. Find the present age of Murali and his father.",
    a: "16, 32 Years",
    b: "15, 30 Years",
    c: "20, 40 Years",
    d: "19, 31 Years",
    answer: "c",
  },
  {
    id: "026",
    question: "The ratio of the present ages of a man and his wife is 5: 8. After 10 years, the ratio of the man and his wife will be 2: 3. What will be the ratio of their ages after 20 years?",
    a: "7:10",
    b: "3:5",
    c: "4:5",
    d: "9:10",
    answer: "a",
  },
  {
    id: "027",
    question: "20 year old Manish is five times as old as his brother Greece. How old will Manish be when he is three times as old as Greece?",
    a: "30",
    b: "24",
    c: "32",
    d: "28",
    answer: "b",
  },
  {
    id: "028",
    question: "After 15 years, a man will be just four times as old as he was 15 years ago. What is his present age?",
    a: "10 Years",
    b: "15 Years",
    c: "20 Years",
    d: "25 Years",
    answer: "d",
  },
  {
    id: "029",
    question: "The ratio of ages of Rahul and his wife after 7 years from now will be 7: 6. If his wife was born 23 years ago, find the age of Rahul after 2 years?",
    a: "25",
    b: "30",
    c: "28",
    d: "40",
    answer: "b",
  },
  {
    id: "030",
    question: "After 5 years, the ratio between ages of A and B will be 5: 8 and after 8 years, the sum of ages will be 71 years. Find the present age of B.",
    a: "35 Years",
    b: "40 Years",
    c: "33 Years",
    d: "32 Years",
    answer: "a",
  },
  // Above datas are Problem on age data...


  {
    id: "031",
    question: "A shopkeeper allows two successive discounts of X% on a shirt which is marked at Rs 2500 and sells it at Rs 1764. Find the selling price of the shirt if the shopkeeper would have given X + 2% of two equal successive discounts?",
    a: "1681",
    b: "2025",
    c: "1936",
    d: "1600",
    answer: "a",
  },
  {
    id: "032",
    question: "By selling an article for Rs 8,670 a man loses 15% At what price (in Rs) should he sell it in order to make a profit of 15%?",
    a: "13,370",
    b: "11,730",
    c: "18,590",
    d: "23,560",
    answer: "b",
  },
  {
    id: "033",
    question: "Varun and Vijay invested Rs. 2500 and Rs. 3250 into a business and after x and (12-x) months they invested Rs. 1000 and Rs. 750 more respectively. If at the end of the year Varun got Rs. 380 out of total annual profit of Rs. 800, Then find the value of 'x'.",
    a: "3",
    b: "5",
    c: "8",
    d: "4",
    answer: "d",
  },
  {
    id: "034",
    question: "Tina and Diya started a shop, with Tina investing an amount 't' and Diya investing an amount 't + d'. After eight months, Tina puts in extra 'd' rupees, while Diya takes out '2d' rupees from her investment. At the year's end, they've earned Rs 8000 in total. How much of that money does Tina get as her share of the profit?",
    a: "2000",
    b: "6000",
    c: "4000",
    d: "5000",
    answer: "c",
  },
  {
    id: "035",
    question: "A bottle with the cost price of Rs. 4500 is marked x% above the cost price and sold after two successive discount of Rs. 140 and 10% respectively for a profit of Rs. 720. A jeans has cost price that is 20% less than that of the bottle. If the selling price of the jeans is Rs.4680 and it is sold at (x - k)% profit then find the value of k?",
    a: "1",
    b: "2",
    c: "3",
    d: "4",
    answer: "b",
  },
  {
    id: "036",
    question: "A shopkeeper earns a profit of 25 percent on selling a radio at 15 percent. discount on the Printed price. Finds the ratio of the Printed price and the cost price of the radio.",
    a: "17:25",
    b: "25:27",
    c: "27:25",
    d: "25:17",
    answer: "d",
  },
  {
    id: "037",
    question: "A shopkeeper normally makes a profit of 20% in a certain transaction; he weights 900 g instead of 1 kg, due to an issue with the weighing machine. If he charges 10% less than what he normally charges, what is his actual profit or loss percentage?",
    a: "20%",
    b: "28%",
    c: "25%",
    d: "30%",
    answer: "a",
  },
  {
    id: "038",
    question: "Two successive discounts of 40% and 20%, respectively, on the marked price of an article are equal to single discount of Rs 988. The marked price (in Rs) of the article is:",
    a: "2470",
    b: "2200",
    c: "1900",
    d: "2070",
    answer: "c",
  },
  {
    id: "039",
    question: "A dishonest merchant sells goods at a 12.5% loss on the cost price, but uses 28 g weight instead of 36 g. What is his percentage profit or loss?",
    a: "6.25% loss",
    b: "12.5% gain",
    c: "18.75% gain",
    d: "10.5% loss",
    answer: "b",
  },
  {
    id: "040",
    question: "Sulekha bought 36 kg of sugar for Rs. 1,040. She sold it at a profit equal to the selling price of 10 kg of it. What is the selling price (in Rs.) for 5 kg of sugar?",
    a: "200",
    b: "215",
    c: "220",
    d: "235",
    answer: "a",
  },
  // Above datas are Profit and loss data...


];
